### ISSUE TITLE
layers of attribution

### ISSUE THREAD

**Issue by diatomsRcool** [globalbioticinteractions/template-dataset#2]
Is there a way to include two layers of attribution in the interactions file? I would like to report the review publication I used and the references they used within.

**Comment by jhpoelen** [comment]
One way to do this is to mention the review article citation as part of the "citation" in globi.json (e.g.
https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/blob/master/globi.json) and the reference as a column named "referenceCitation" (referenceDoi if you have one) in the interactions.tsv file (e.g. https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/blob/master/interactions.tsv).

Let me know if this works for you. If not, please propose alternate so that we can figure out a way to make it better.

**Comment by diatomsRcool** [comment]
OK, I think this will work.
